apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: demo:0.0.1-SNAPSHOT
        name: demo
        ports:
        - containerPort: 8080
        env:
          - name: K8S_NAMESPACE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: K8S_POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: K8S_POD_UID
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.uid
          - name: K8S_CONTAINER_NAME
            value: demo
          - name: OTEL_JAVAAGENT_ENABLED
            value: 'true'
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            # Replace this with the actual OTLP endpoint you want to use
            value: *otlp-endpoint
          - name: OTEL_EXPORTER_OTLP_HEADERS
            # Replace this with the HTTP headers your OTLP endpoint requires for authorization
            value: *otlp-auth-headers
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: k8s.namespace.name=$(K8S_NAMESPACE_NAME),k8s.pod.name=$(K8S_POD_NAME),k8s.pod.uid=$(K8S_POD_UID),k8s.container.name=$(K8S_CONTAINER_NAME)
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3